// Mock data for development/testing
export const mockMerchant = {
  id: 'merchant-1',
  user_id: 'user-1',
  merchant_id: 'MERCH001',
  merchant_name: 'Mais Suppliers',
  merchant_email: 'merchant@example.com',
  merchant_phone: '+255123456789',
  merchant_location: 'Dar es Salaam',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}

export const mockInventory = [
  {
    id: 'inv-1',
    merchant_id: 'MERCH001',
    product_id: 'PROD001',
    product_name: 'Cooking Oil (5L)',
    current_stock: 85,
    minimum_stock: 20,
    maximum_stock: 100,
    status: 'good' as const,
    last_updated: new Date().toISOString(),
  },
  {
    id: 'inv-2',
    merchant_id: 'MERCH001',
    product_id: 'PROD002',
    product_name: 'Sugar (kg)',
    current_stock: 45,
    minimum_stock: 30,
    maximum_stock: 80,
    status: 'good' as const,
    last_updated: new Date().toISOString(),
  },
  {
    id: 'inv-3',
    merchant_id: 'MERCH001',
    product_id: 'PROD003',
    product_name: 'Rice (50kg)',
    current_stock: 35,
    minimum_stock: 25,
    maximum_stock: 100,
    status: 'warning' as const,
    last_updated: new Date().toISOString(),
  },
  {
    id: 'inv-4',
    merchant_id: 'MERCH001',
    product_id: 'PROD004',
    product_name: 'Beans (kg)',
    current_stock: 8,
    minimum_stock: 15,
    maximum_stock: 60,
    status: 'danger' as const,
    last_updated: new Date().toISOString(),
  },
  {
    id: 'inv-5',
    merchant_id: 'MERCH001',
    product_id: 'PROD005',
    product_name: 'Flour (25kg)',
    current_stock: 70,
    minimum_stock: 20,
    maximum_stock: 100,
    status: 'good' as const,
    last_updated: new Date().toISOString(),
  },
  {
    id: 'inv-6',
    merchant_id: 'MERCH001',
    product_id: 'PROD006',
    product_name: 'Salt (kg)',
    current_stock: 5,
    minimum_stock: 10,
    maximum_stock: 50,
    status: 'danger' as const,
    last_updated: new Date().toISOString(),
  },
]

export const mockOrderItems = [
  { id: 'item-1', order_id: 'order-1', product_id: 'PROD001', quantity: 5 },
  { id: 'item-2', order_id: 'order-1', product_id: 'PROD002', quantity: 3 },
  { id: 'item-3', order_id: 'order-2', product_id: 'PROD001', quantity: 2 },
  { id: 'item-4', order_id: 'order-3', product_id: 'PROD003', quantity: 10 },
  { id: 'item-5', order_id: 'order-3', product_id: 'PROD004', quantity: 4 },
  { id: 'item-6', order_id: 'order-4', product_id: 'PROD002', quantity: 6 },
]

export const mockOrders = [
  {
    id: 'order-1',
    order_id: 'ORD-001',
    merchant_id: 'MERCH001',
    customer_name: 'John Retail Store',
    customer_phone: '+255654321098',
    status: 'pending',
    total_amount: 125000,
    created_at: new Date(Date.now() - 5 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 60000).toISOString(),
    items: [
      { product_id: 'PROD001', product_name: 'Cooking Oil (5L)', quantity: 5 },
      { product_id: 'PROD002', product_name: 'Sugar (kg)', quantity: 3 },
    ],
  },
  {
    id: 'order-2',
    order_id: 'ORD-002',
    merchant_id: 'MERCH001',
    customer_name: 'Quick Mart',
    customer_phone: '+255123456789',
    status: 'pending',
    total_amount: 85000,
    created_at: new Date(Date.now() - 10 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 60000).toISOString(),
    items: [
      { product_id: 'PROD001', product_name: 'Cooking Oil (5L)', quantity: 2 },
    ],
  },
  {
    id: 'order-3',
    order_id: 'ORD-003',
    merchant_id: 'MERCH001',
    customer_name: 'Downtown Shop',
    customer_phone: '+255987654321',
    status: 'pending',
    total_amount: 245000,
    created_at: new Date(Date.now() - 15 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 60000).toISOString(),
    items: [
      { product_id: 'PROD003', product_name: 'Rice (50kg)', quantity: 10 },
      { product_id: 'PROD004', product_name: 'Beans (kg)', quantity: 4 },
    ],
  },
  {
    id: 'order-5',
    order_id: 'ORD-005',
    merchant_id: 'MERCH001',
    customer_name: 'Elite Supermarket',
    customer_phone: '+255741852963',
    status: 'pending',
    total_amount: 320000,
    created_at: new Date(Date.now() - 20 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 60000).toISOString(),
    items: [
      { product_id: 'PROD001', product_name: 'Cooking Oil (5L)', quantity: 8 },
      { product_id: 'PROD002', product_name: 'Sugar (kg)', quantity: 5 },
      { product_id: 'PROD005', product_name: 'Flour (25kg)', quantity: 2 },
    ],
  },
]
